from pylab import *

cal = np.loadtxt('ex1.txt', skiprows=2)
ph  = cal[:, 0]

ax1 = subplot(2, 2, 1)
semilogy(ph, cal[:, 1], 'b-', ph, cal[:, 2], 'r-', ph, cal[:, 3], 'g-', ph, cal[:, 4], 'm-', ph, cal[:, 5], 'c-') 
plt.xlim([1, 11])
plt.ylim([1.0e-30, 1.0e-5])
plt.ylabel('M')
plt.yticks([1e-30, 1e-25, 1e-20, 1e-15, 1e-10, 1e-5])
lgd = plt.legend(('Hg$^{2+}$', 'HgOH$^+$', 'Hg(OH)$_2$', 'Hg(OH)${_3}{^-}$', 'Hg$_2$OH$^{3+}$'),loc=3)
lgd.draw_frame(False)
txt = lgd.get_texts()
plt.setp(txt, fontsize='small')
plt.setp(ax1.get_xticklabels(),visible=False)

ax2 = subplot(2, 2, 2)
semilogy(ph, cal[:, 6], 'b-', ph, cal[:, 7], 'r-', ph, cal[:, 8], 'g-', ph, cal[:, 9], 'm-', ph, cal[:, 10], 'c-') 
plt.xlim([1, 11])
plt.ylim([1.0e-30, 1.0e-5])
plt.yticks([1e-30, 1e-25, 1e-20, 1e-15, 1e-10, 1e-5])
lgd = plt.legend(('Hg$_3$(OH)${_3}^{3+}$', 'HgOHCl', 'HgOHCO${_3}{^-}$', 'HgF$^+$', 'HgCl$^+$'),loc=3)
lgd.draw_frame(False)
txt = lgd.get_texts()
plt.setp(txt, fontsize='small')
plt.setp(ax2.get_xticklabels(),visible=False)
plt.setp(ax2.get_yticklabels(),visible=False)

ax3 = subplot(2, 2, 3)
semilogy(ph, cal[:, 11], 'b-', ph, cal[:, 12], 'r-', ph, cal[:, 13], 'g-', ph, cal[:, 14], 'm-', ph, cal[:, 15], 'c-') 
plt.xlim([1, 11])
plt.ylim([1.0e-30, 1.0e-5])
plt.xlabel('pH')
plt.ylabel('M')
plt.yticks([1e-30, 1e-25, 1e-20, 1e-15, 1e-10, 1e-5])
lgd = plt.legend(('HgCl$_2$', 'HgCl${_3}{^-}$', 'HgCl${_4}{^{2-}}$', 'HgHCO${_3}{^+}$', 'HgCO$_3$'),loc=3)
lgd.draw_frame(False)
txt = lgd.get_texts()
plt.setp(txt, fontsize='small')

ax4 = subplot(2, 2, 4)
semilogy(ph, cal[:, 16], 'b-', ph, cal[:, 17], 'r-', ph, cal[:, 18], 'g-', ph, cal[:, 19], 'm-', ph, cal[:, 20], 'c-') 
plt.xlim([1, 11])
plt.ylim([1.0e-30, 1.0e-5])
plt.xlabel('pH')
plt.yticks([1e-30, 1e-25, 1e-20, 1e-15, 1e-10, 1e-5])
lgd = plt.legend(('Hg(CO$_3$)${_2}^{2-}$', 'HgHPO$_4$', 'HgPO${_4}^{-}$', 'HgSO$_4$', 'Hg(SO$_4$)${_2}{^{2-}}$', 'HgNO${_3}{^+}$', 'Hg(NO$_3$)$_2$'),loc=3)
lgd.draw_frame(False)
txt = lgd.get_texts()
plt.setp(txt, fontsize='small')
plt.setp(ax4.get_yticklabels(),visible=False)

plt.subplots_adjust(left=0.12, right=0.95, top=0.95, bottom=0.12, wspace=0.05, hspace=0.05)

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(8, 6)
savefig('ex1.png')
savefig('ex1.pdf')
#show()
